# Generated by Django 5.0.6 on 2024-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='request_received',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='request_sent',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
