# Generated by Django 5.0.6 on 2024-06-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_profile_friend_list_profile_request_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_list',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='request_received',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='request_sent',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
